# Generated by Django 6.0.3 on 2026-03-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='date',
            field=models.DateField(),
        ),
    ]
